site_name: WideQuick Water & Wastewater Treatment
theme:
  features:
    - navigation.indexes

  name: null
  custom_dir: mkdocs-material/material

  palette:
    scheme: wqva

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Sans Pro
    code: Sans
  favicon: assets/logo.svg

  logo: assets/logo.svg

extra_css:
  - overrides/stylesheets/extra.css

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - admonition

copyright: Copyright &copy 2000-2022 Kentima AB

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kentima-solutions/
      name: Kentima on LinkedIn
